// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz_RhVmBRk0MQpcioXAQ0v1_ZHRzo7bJI',
    appId: '1:15041481805:ios:9679ef5d916fce27b92004',
    messagingSenderId: '15041481805',
    projectId: 'fir-login-24df1',
    storageBucket: 'fir-login-24df1.appspot.com',
    androidClientId: '15041481805-srjniv6ha4jfbc7evgei1eutr9o9iuev.apps.googleusercontent.com',
    iosClientId: '15041481805-3od3i26qnnrrvo6tfrgag8du7f4s7uct.apps.googleusercontent.com',
    iosBundleId: 'com.example.network',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1DtfEiXzQSf361Egf8OzREqEzy7r6OzE',
    appId: '1:15041481805:web:f533bac69b00b254b92004',
    messagingSenderId: '15041481805',
    projectId: 'fir-login-24df1',
    authDomain: 'fir-login-24df1.firebaseapp.com',
    storageBucket: 'fir-login-24df1.appspot.com',
    measurementId: 'G-5NKT7N3RDN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNzudmVV1idVEmv8x4DQmn9bsd7SN1RQ',
    appId: '1:15041481805:web:d07cfc93c559764bb92004',
    messagingSenderId: '15041481805',
    projectId: 'fir-login-24df1',
    authDomain: 'fir-login-24df1.firebaseapp.com',
    storageBucket: 'fir-login-24df1.appspot.com',
    measurementId: 'G-8HWV7X7QZF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_RhVmBRk0MQpcioXAQ0v1_ZHRzo7bJI',
    appId: '1:15041481805:ios:9679ef5d916fce27b92004',
    messagingSenderId: '15041481805',
    projectId: 'fir-login-24df1',
    storageBucket: 'fir-login-24df1.appspot.com',
    androidClientId: '15041481805-srjniv6ha4jfbc7evgei1eutr9o9iuev.apps.googleusercontent.com',
    iosClientId: '15041481805-3od3i26qnnrrvo6tfrgag8du7f4s7uct.apps.googleusercontent.com',
    iosBundleId: 'com.example.network',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJyQXy25AijrXGagADuY3xLaEAMcm4qQ',
    appId: '1:15041481805:android:e016715bff9c43bbb92004',
    messagingSenderId: '15041481805',
    projectId: 'fir-login-24df1',
    storageBucket: 'fir-login-24df1.appspot.com',
  );

}